### ISSUE TITLE
Support setting harfbuzz buffer flags

### ISSUE THREAD

**Issue by norbusan** [latex3/luaotfload#113]
Current luaharfbuzz exports more functionality, see https://github.com/ufyTeX/luaharfbuzz/pull/46 in particular it enables setting harfbuzz buffer flags.

I would like to have a way to set flags per font, and propose
```
RawFeature={mode=harf;flags=FLAG_XXX|FLAG_YYY}
```
As an example, I could load a Tibetan font with
```
\newfontface{\tibDDC}[RawFeature={mode=harf;script=tibt;flags=FLAG_DO_NOT_INSERT_DOTTED_CIRCLE}]{DDC-Uchen.ttf}
```

I have made a completely beginner shot at an implementation:
```
+++ b/src/luaotfload-harf-define.lua
@@ -376,6 +376,8 @@ fonts.readers.harf = function(spec)
         val = '+'..key..'='..tonumber(val) - 1
         hb_features[#hb_features + 1] = hb.Feature.new(val)
       end
+    elseif key == "flags" then
+      spec.flags = val
     end
   end
   return scalefont(loadfont(spec), spec)
```

and
```
--- a/src/luaotfload-harf-plug.lua
+++ b/src/luaotfload-harf-plug.lua
@@ -325,11 +326,31 @@ function shape(head, node, run)
   local lang = spec.language or invalid_l
   local script = spec.script or invalid_s
   local shapers = options.shaper and { options.shaper } or {}
+  local hb_buffer_flags = spec.flags or {}
 
   local buf = hb.Buffer.new()
   buf:set_direction(dir)
   buf:set_script(script)
   buf:set_language(lang)
+  -- get flags from the spec
+  -- RawFeature={mode=harf;script=tibt;flags=FLAG_DO_NOT_INSERT_DOTTED_CIRCLE|FLAG_YYY}
+  if hb_buffer_flags then
+    -- todo, we don't support multiple flags here
+    log.report("log", 0, "harfflags", "setting buffer flags " + flags)
+    local flagsval = { llpeg.splitat(",", hb_buffer_flags) }
+    local finalflag = 0
+    for f in flagsval do
+      if hb.Buffer[f] then
+        finalflag |= hb.Buffer[f]
+      else
+       log.report("error", 0, "harfflags", "unknown flag " + f)
+      end
+    end
+    if finalflag = 0 then
+      finalflag = hb.Buffer.FLAG_DEFAULT
+    end
+    buf:set_flags(finalflag)
+  end
   buf:set_cluster_level(buf.CLUSTER_LEVEL_MONOTONE_CHARACTERS)
   buf:add_codepoints(codes, offset - 1, len)
 ```

This of course only works when the patch from the above PR (already merged) is built into the luahbtex binary (which I have done for now).

It would also need checks on the availability of `buf:set_flags` but I am not sure how this can be done.

Just as an idea.

Thanks

**Comment by zauguin** [comment]
I have a implementation for something like this ready, but it will have a different interface to fit into regular features and is fontloader compatible where that makes sense. So instead of exposing flags directly, we add support for setting the pseudo feature `ignorables` and a new feature (`dotted_circle`? I didn't find a good name yet).

Currently this is waiting for upstream support, I think adding it now would mostly be confusing because this isn't merged to LuaTeX yet.

**Comment by norbusan** [comment]
Hi Marcel,

Sorry, I could have guessed that you have something ready already ;-) I have no preference for the interface whatsoever, as long as the functionality is here.

Concerning the name, `no_dotted_circle` would probably the appropriate feature name.

Can I see the current code, since I have already a patched luahbtex with support for these flags.

Thanks for all your work!!!

Norbert

**Comment by zauguin** [comment]
@norbusan 
I fixed some stuff and uploaded it to the `flags-dev` branch. This is highly experimental code and might change in any way.

The syntax is: Dotted circles are inserted by default via the feature `dottedcircle`, it can be disables by adding the feature string `-dottedcircle` or `dottedcircle=false`. Also `invisible=false`/`-invisible` is now respected for HarfBuzz fonts too. `invisible=remove` ensures that invisible characters are completly removed.

**Comment by norbusan** [comment]
@zauguin Thanks a lot, I have tried it works in some cases, and in some not. Well, at least it shows that principally it is possible. I attach two files (tibetan-test.pdf and tibetan-test-nodot.pdf) where both are created with the same luahbtex and luaotfload, only the font definition in the later case includes the `-dottedcircle`).

Thanks for your work!
[tibetan-test.pdf](https://github.com/latex3/luaotfload/files/3796510/tibetan-test.pdf)
[tibetan-test-nodot.pdf](https://github.com/latex3/luaotfload/files/3796511/tibetan-test-nodot.pdf)

**Comment by zauguin** [comment]
> @zauguin Thanks a lot, I have tried it works in some cases, and in some not. Well, at least it shows that principally it is possible.

Do you mean that disabling the insertion of the dotted circle sometimes doesn't work or that even without the circle you still don't get output you hoped for? If I don't miss anything the only circles left are the one which are part of the Jomolhori glyphs.

**Comment by norbusan** [comment]
Yes indeed, only Jomolhari is still broken, this font is nice but somehow completely off the point it seems. I probably was surprised about the layout with Noto in the colored line which comes from the following input:
```
{\color{blue}ༀ}{\color{red}ྰ}
```
but that is a special case (btw, it would be nice if coloring of parts would be possible? Is there any way to achieve this? Probably not due to lookups into precomposed glyphs).

**Comment by norbusan** [comment]
PS: I will try to contact a colleague who had a **lot** of dotted circles with Bangla ...

**Comment by zauguin** [comment]
> Yes indeed, only Jomolhari is still broken, this font is nice but somehow completely off the point it seems. I probably was surprised about the layout with Noto in the colored line which comes from the following input:
> 
> ```
> {\color{blue}ༀ}{\color{red}ྰ}
> ```
> 
> but that is a special case (btw, it would be nice if coloring of parts would be possible? Is there any way to achieve this? Probably not due to lookups into precomposed glyphs).

It depends: Everything which is shown as a single glyph of the font will always have a single color (except if the font has color glyph support). If the parts are separate glyphs and no reordering is done, then coloring parts of parts should work. This will normally require the use of the `luacolor` package, otherwise shaping is interrupted by the color whatsits 
So you could try if you get better output after loading `luacolor`.

**Comment by zauguin** [comment]
> PS: I will try to contact a colleague who had a **lot** of dotted circles with Bangla ...

If he got a lot of dotted circles, please try to fix the underlying problem. Especially for such scripts as Bengali, just suppressing the dotted circles will not lead to optimal output.

Has he tried all versions of Bengali shaping (script tags `beng`, `bng2` and `bng3`?) I would expect `bng2` to give the best result, but that probably depends on the font.

Also could your colleague contribute a test file?

**Comment by norbusan** [comment]
Hi @zauguin 
thanks for the hint regarding luacolor, didn't know about it. And yes, this is what I supposed, since all glyphs are more or less precomposed and **should** be used by lua(hb)tex, and if they aren't, that should be fixed in (luatex|harfbuzz).

Concerning the Bengali shaping, I will check. I have some test files and will see what is the outcome. Only problem - my Bengali is not really up to standards (or better 0).
