### ISSUE TITLE
LuaHBTeX:  \copy contents behave differently from \box for copy-paste — by making contents tofu 􀈽 for reordered glyphs or by adding spurious space

### ISSUE THREAD

**Issue by reportaman** [latex3/luaotfload#171]
## Brief outline of the bug
While using HarfBuzz, the searchable/copyable contents added to pdf is different for `\box` and it's `\copy`. The following example was [first posted as a question on TeX.SE](https://tex.stackexchange.com/q/566023/192717), its being asked here as it might be a core LuaHBTeX bug.

Here's an example of a tex `\vbox` with some devanagari text in it. My code adds contents of `\vbox` to document twice, first its copy (using `\copy`), and later itself (using `\box`). Both copies look similarly typeset in pdf, which is great. But upon copy-pasting contents from the pdf,<sup>\[1\]</sup> I find that the contents added by `\copy` look different from the contents added by `\box`. The former has some glyphs turned into tofu `􀈽`; looks like the only glyph tofued is reordered [Devanagari](https://www.compart.com/en/unicode/block/U+0900) vowel sign ` ि` i.e. [U+093F](https://www.compart.com/en/unicode/U+093F). The latter doesn't tofu anything, but adds extra spurious space after the consonant-vowel pairs where ` ि` is the consonant.

<sup>\[1\]</sup> I used Adobe Reader as it seems to be the only pdf reader that fully supports ActualText feature of pdf format that HarfBuzz utilizes.

## Minimal example showing the bug

> __NOTE: package `fontspec` is needed as thats the only way I know to load the font.__

```latex
% Please comment following line "\RequirePackage{latexbug}" before running, it is added here only because that's required by your documentation
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\pagenumbering{gobble}
\usepackage{fontspec}
\newfontfamily\devanagarifont[Script=Devanagari, Renderer=HarfBuzz, Ligatures=TeX]{Noto Sans Devanagari}

\begin{document}

\newbox\tempbox
\setbox\tempbox=\vbox{{\devanagarifont किं बहुना । परस्परं द्वैधम् उत्पन्नम् । पिताजी ज्योतिषी सुकरात\endgraf}}

Box copy: \copy\tempbox

Box contents: \box\tempbox

\end{document}
```

Result of copy-paste:

> Box copy: 􀈽कंबहुना । परस्परंद्वै धम्उत्पन्नम्। 􀈱पताजी ज्यो􀈱तषी सुकरात
> 
> Box contents: कि ं बहुना । परस्परंद्वै धम्उत्पन्नम्। पि ताजी ज्योति षी सुकरात

As can be seen, the 3 tofus `􀈽` placed in "Box copy" contents are for vowel notation ` ि` of consonant-vowel pairs: `कि`, `पि`, and `ति`. Also to be noticed is that this tofuing process gobbles word space, and makes `किं बहुना` as one word `􀈽कंबहुना`.  The "Box contents" has correct glyphs, but has extra spacing after same consonant-vowel pairs `कि`, `पि`, and `ति`. The original box contents luckily doesn't gobble space between words `किं` and `बहुना`. So IMO if `\box` contents get rid of extra space after consonant-vowel pairs & if contents added to pdf by `\copy` are same as those added by `\box`, then this copy-paste problem should get resolved.

Side note for `Renderer=Node`: Tofu and spurious spacing problem does not occur with Node renderer. Though it has its own known problem of reordering ` ि` and consonant of its consonant-vowel pair.

## Log file (required) and possibly PDF file  

[hbcopy.log](https://github.com/latex3/latex2e/files/5396775/hbcopy.log)
[hbcopy.pdf](https://github.com/latex3/latex2e/files/5396776/hbcopy.pdf)

**Comment by zauguin** [comment]
This has been fixed in 5aa32d3864d418de12483aa17e5eaaaac0106053 (currently in the dev branch) and therefore should work after the next luaotfload release.

**Comment by FrankMittelbach** [comment]
small side remark

> ```
> % Please comment following line "\RequirePackage{latexbug}" before running, it is added here only because that's required by your documentation
> \RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
> ```

well there is a reason for the line ... it tells you that your example uses code that we do not support and therefore (usually) can't help and that it should therefore be reported elsewhere. Although my guess was that it isn't a fontspec problem but a  luaotfload problem as confirmed by @zauguin .

**Comment by u-fischer** [comment]
just for the record: I did answer your question on the luatex list there three days ago that it is a luaotfload issue and that it has been resolved.

**Comment by reportaman** [comment]
@FrankMittelbach Yes, `latexbug` reported that I should report issue on `fontspec.sty`. I knew its not a fontspec issue, though had no clue its is `luaotfload` issue or somewhere else in implementation `luahbtex`. I was looking for a `luatex` or `luahbtex` GitHub repository to file a bug and didn't find one, that made me decide to file it on latex GitHub as it seemed the only repo for "core" functionality. 

@zauguin One problem still exists, its the spurious space added after reordered glyph pair (Node renderer doesn't do that). The mismatch between `\copy` and `\box` is gone in luaotfload dev branch you point, thanks for that! Should I file another bug on luaotfload/fonstpec for the spurious space? 

@u-fischer: Just checked again, I did not receive an email. Do I need to sign-up on some list to be able to see replies? Thanks

**Comment by u-fischer** [comment]
My answer is in the archive https://tug.org/pipermail/luatex/2020-October/thread.html. I have no idea what you must do to get it. I read such lists through gmane or through the archive.

**Comment by zauguin** [comment]
> Yes, `latexbug` reported that I should report issue on `fontspec.sty`. I knew its not a fontspec issue, though had no clue its is `luaotfload` issue or somewhere else in codebase of `luahbtex`. I was looking for a `luatex` or `luahbtex` GitHub repository to file a bug and didn't find one, that made me decide to file it on latex GitHub as it seemed the only repo for "core" functionality.

As a general guideline font issues in LuaLaTeX are almost never `luahbtex` issues (The font handling is mostly left to Lua code), so the LaTeX repo was a reasonable guess.
FYI, to load the font without fontspec, you could e.g.  use the `\font` primitive (Don't do this in an actual LaTeX document)

    \font\devanagarifont "Noto Sans Devanagari:script=dev2;mode=harf;+tlig" at 10pt

or use NFSS (You can use this in an actual document, but then you probably want to add e.g. a bold shape) (This is roughly what fontspec is doing)

```
\DeclareFontFamily{TU}{noto-deva}{}
\DeclareFontShape{TU}{noto-deva}{m}{n}{%
  <-> \UnicodeFontName{Noto Sans Devanagari}{\UnicodeFontTeXLigatures script=dev2;mode=harf;}%
}{}%
\newcommand\devanagarifont{\fontfamily{noto-deva}\selectfont}
```

>  One problem still exists, its the spurious space added after reordered glyph pair (...). Should I file another bug on luaotfload/fonstpec for the spurious space?

Feel free to do so (in luaotfload) but be warned that this will be at best a long-term feature request. Your PDF reader tries to deduce the position of spaces on it's own and there is not much we can do to influence this reliably. (We *can* add missing spaces by making them explicit, but *suppressing* is more complicated.)

> Just checked again, I did not receive an email. Do I need to sign-up on some list to be able to see replies? Thanks

It depends a bit on who is answering, but in general you will see answers more reliably by watching the archive or subscribing to the list. ([For the `luatex` list, you can do so here](https://tug.org/mailman/listinfo/luatex))

**Comment by reportaman** [comment]
@zauguin Thanks! I went through your code, and had a suspicion that turned correct. Given you moved things to post linebreak filter, the problem persists where it is not called. That will happen when linebreak is not done, for instance when text set in a `\hbox` instead of `\vbox`, try this and it will give same problem of tofu:

```
\setbox0=\hbox{\devanagarifont किं  बहुना । परस्परं द्वैधम् उत्पन्नम् । पिताजी ज्योतिषी सुकरात}
\box0
```

I tried your dev branch code on a much longer Devanagari test case, and am happy to say that the only problematic cases (the one that add extra spacing) is where there is subset of word that is put as ActualText entry & there was some glyph reordering (probably because it is shaped by Harf??). I wonder if it has more to do with transitioning from ActualText entry to stream in the middle of the word rather than actual spacing in pdf (tough I haven't tested it so idk). My viewer is acrobat reader (free), as none other seem to work with ActualText. I will file a ticket for spacing issue later.

**Comment by zauguin** [comment]
> @zauguin Thanks! I went through your code, and had a suspicion that turned correct. Given you moved things to post_linebreak filter, the problem persists where it is not called. That will happen when linebreak is not done, for instance when text is set in a `\hbox` instead of `\vbox`, try this and it will give same tofu problem:
> 
> ```
> \setbox0=\hbox{\devanagarifont किं  बहुना । परस्परं द्वैधम् उत्पन्नम् । पिताजी ज्योतिषी सुकरात}
> \box0
> ```

Actually the code *was* called for hbox'es (through `hpack_filter`) but there was some ordering issue such that it got called too early. Anyway it's fixed now.

> 
> I tried your dev branch code on a much longer Devanagari test case, and am happy to say that the only problematic cases (the one that add extra spacing) is where there is subset of word that is put as ActualText entry & there was some glyph reordering (probably because it is shaped by Harf??). I wonder if it has more to do with transitioning from ActualText entry to text stream in the middle of the word rather than actual spacing in pdf that makes pdf viewer add space at that point. Perhaps they never thought ActualText would be used for subset of a word (though idk).

ActualText is intended for such use cases, there is even a note in the specification:

> NOTE 2
> The treatment of ActualText as a character replacement is different from the treatment of Alt, which is treated
as a whole word or phrase substitution.

But I think that you are partially right and our placement of the text markers outside of text objects at least plays a significant part in this issue. Avoiding this leads to issues though because it would lead to invalid PDF files as soon as color fonts and/or external code injecting nodes at the wrong places get involved. I am somewhat hopeful that we will be able to deal with this when we have a general tagging system in place though.

> My viewer is acrobat reader (free version) as none other seem to work with ActualText. I will file a ticket for spacing issue later.

I can suggest okular as an open viewer which works with ActualText if you want to try it somewhere else. (It shows exactly the same issue though)

**Comment by u-fischer** [comment]
The next luaotfload version 3.16 has been uploaded. This should fix the issue.
